host: login.salesforce.com        # Use test.salesforce.com for sandbox
client_secret: 1429502758603984138         # This is the Consumer Secret from Salesforce
client_id: 3MVG9sG9Z3Q1RlbcJOtyQTrZhWRJDLW_llUaVX53itGqT4jBNfYqxduB5DFQiRXsqh5n1O9bFHBGkRsvCrnI6    # This is the Consumer Key from Salesforce
       # See below for details on using modules
debugging: true                   # Can be useful while developing
username: user@theforce.com
password: interns15S1BzdwyzMAO0NfkTWYxVZfgk